/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ARQUIVO_H_RPCGEN
#define _ARQUIVO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct arquivo {
	int id[7];
	char nome[100];
	char conteudo[1000];
};
typedef struct arquivo arquivo;

#define opera_arquivos 9999
#define opera_arquivos1 100

#if defined(__STDC__) || defined(__cplusplus)
#define criar_arquivo 1
extern  int * criar_arquivo_100(arquivo *, CLIENT *);
extern  int * criar_arquivo_100_svc(arquivo *, struct svc_req *);
#define deletar_arquivo 2
extern  int * deletar_arquivo_100(arquivo *, CLIENT *);
extern  int * deletar_arquivo_100_svc(arquivo *, struct svc_req *);
#define copiar_arquivo 3
extern  int * copiar_arquivo_100(arquivo *, CLIENT *);
extern  int * copiar_arquivo_100_svc(arquivo *, struct svc_req *);
#define escrever_arquivo 4
extern  int * escrever_arquivo_100(arquivo *, CLIENT *);
extern  int * escrever_arquivo_100_svc(arquivo *, struct svc_req *);
#define ler_arquivo 5
extern  int * ler_arquivo_100(arquivo *, CLIENT *);
extern  int * ler_arquivo_100_svc(arquivo *, struct svc_req *);
extern int opera_arquivos_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define criar_arquivo 1
extern  int * criar_arquivo_100();
extern  int * criar_arquivo_100_svc();
#define deletar_arquivo 2
extern  int * deletar_arquivo_100();
extern  int * deletar_arquivo_100_svc();
#define copiar_arquivo 3
extern  int * copiar_arquivo_100();
extern  int * copiar_arquivo_100_svc();
#define escrever_arquivo 4
extern  int * escrever_arquivo_100();
extern  int * escrever_arquivo_100_svc();
#define ler_arquivo 5
extern  int * ler_arquivo_100();
extern  int * ler_arquivo_100_svc();
extern int opera_arquivos_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_arquivo (XDR *, arquivo*);

#else /* K&R C */
extern bool_t xdr_arquivo ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ARQUIVO_H_RPCGEN */
