/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arquivo.h"
#include <stdio.h>



void
opera_arquivos_100(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	arquivo  criar_arquivo_100_arg;
	int  *result_2;
	arquivo  deletar_arquivo_100_arg;
	int  *result_3;
	arquivo  copiar_arquivo_100_arg;
	int  *result_4;
	arquivo  escrever_arquivo_100_arg;
	int  *result_5;
	arquivo  ler_arquivo_100_arg;
	int opc;
	int op;
	int x;
	char nome_arq_copiar[100];
	char nome_arq_criado[100];
	char ext[5]=".txt";
	char nome[100];

#ifndef	DEBUG
	clnt = clnt_create (host, opera_arquivos, opera_arquivos1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
do{
	printf("------------------- SISTEMA DE ARQUIVOS DISTRIBUÍDOS -----------------------\n");
	printf("1 - CRIAR ARQUIVO\n");
	printf("2 - DELETAR ARQUIVO\n");
	printf("3 - COPIAR ARQUIVO\n");
	printf("4 - ESCREVER EM ARQUIVO\n");
	printf("5 - LER ARQUIVO\n");
	printf("0 - SAIR\n");
	printf("-----------------------------------------------------------------------------\n");
	printf("ESCOLHA SUA OPÇÃO: \n");
	scanf("%d", &opc);

	

	if(opc == 1){
		printf("Digite o nome do arquivo a ser criado: \n");
		scanf("%s",&nome);
		strcat(nome,ext);
		strcpy(criar_arquivo_100_arg.nome,nome);
		result_1 = criar_arquivo_100(&criar_arquivo_100_arg, clnt);

		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "A chamada ao método criar remoto falhou.");
		}else{
			if(*result_1 == 0){
				printf("Algo deu errado.\n");			
			}else{
				printf("Operação CRIAR ARQUIVO realizada com sucesso.\n");
			}
		}
	}
	if(opc == 2){
		printf("Digite o nome do arquivo a ser deletado: \n");
		scanf("%s",&deletar_arquivo_100_arg.nome);

		result_2 = deletar_arquivo_100(&deletar_arquivo_100_arg, clnt);
		if (result_2 == (int *) NULL) {
			clnt_perror (clnt, "A chamada ao método deletar remoto falhou.");
		}else{
			if(*result_2 != 0){
				printf("Algo deu errado.\n");			
			}else{
				printf("Operação DELETAR ARQUIVO realizada com sucesso.\n");
			}
		}
	}
	if(opc == 3){

		printf("Deseja copiar arquivo: 1 - Novo | 2 - Existente");
		scanf("%d", &op);

		if(op == 1){
			printf("Digite o nome do arquivo a ser criado: ");
			scanf("%s", &copiar_arquivo_100_arg.nome);
			printf("\n");
			strcat(copiar_arquivo_100_arg.nome,ext);
			x = criar_arquivo_100(&copiar_arquivo_100_arg, clnt);
			if(x == 0){
				printf("Algo deu errado\n");
			}else{
				printf("Arquivo criado com sucesso\n");
				printf("Digite o nome do arquivo que você deseja copiar:");
				fflush(stdin);
				scanf("%s", &nome_arq_copiar);
				strcat(nome_arq_copiar,ext);
			
				strcpy(nome_arq_criado,copiar_arquivo_100_arg.nome);
				strcat(nome_arq_copiar," ");
				strcat(nome_arq_copiar,nome_arq_criado);
				strcpy(copiar_arquivo_100_arg.nome,nome_arq_copiar);
		
				printf("O nome do arquivo agr é %s\n", copiar_arquivo_100_arg.nome);
			
				result_3 = copiar_arquivo_100(&copiar_arquivo_100_arg, clnt);
				if (result_3 == (int *) NULL) {
				clnt_perror (clnt, "A chamada ao método copiar remoto falhou.");
				}else{
					printf("Operação COPIAR ARQUIVO realizada com sucesso.\n");
				}
			}	
		}else{
			printf("Digite o nome do arquivo para o qual você deseja copiar: ");
			scanf("%s", &copiar_arquivo_100_arg.nome);
			printf("\n");
			strcat(copiar_arquivo_100_arg.nome,ext);
			
			printf("Digite o nome do arquivo que você deseja copiar:");
			fflush(stdin);
			scanf("%s", &nome_arq_copiar);
			strcat(nome_arq_copiar,ext);
			
			strcpy(nome_arq_criado,copiar_arquivo_100_arg.nome);
			strcat(nome_arq_copiar," ");
			strcat(nome_arq_copiar,nome_arq_criado);
			strcpy(copiar_arquivo_100_arg.nome,nome_arq_copiar);
		
			printf("O nome do arquivo agr é %s\n", copiar_arquivo_100_arg.nome);
			
			result_3 = copiar_arquivo_100(&copiar_arquivo_100_arg, clnt);
			if (result_3 == (int *) NULL) {
				clnt_perror (clnt, "A chamada ao método copiar remoto falhou.");
			}else{
				printf("Operação COPIAR ARQUIVO realizada com sucesso.\n");
			}
				
		

		}	
		
	}
	if(opc == 4){
		printf("Deseja escrever em arquivo: 1 - Novo | 2 - Existente\n");
		scanf("%d",&op);
		if(op == 1){
			printf("Digite o nome do arquivo a ser criado: \n");
			scanf("%s", &escrever_arquivo_100_arg.nome);
			x = criar_arquivo_100(&escrever_arquivo_100_arg, clnt);
			if(x == 0){
				printf("Algo deu errado\n");
			}else{
				printf("Arquivo criado com sucesso\n");
			}
			printf("Digite o que deseja inserir no arquivo: \n");
			fflush(stdin);
			scanf(" %[^\n]s",&escrever_arquivo_100_arg.conteudo);;

			result_4 = escrever_arquivo_100(&escrever_arquivo_100_arg, clnt);
			if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "A chamada ao método escrever remoto falhou.");
			}else{
				if(*result_4 == 0){
					printf("Algo deu errado.");				
				}else{
					printf("Operação ESCREVER NO ARQUIVO realizada com sucesso.\n");
				}
			}
			
		}else{
			printf("Digite o nome do arquivo no qual deseja escrever: \n");
			scanf("%s", &escrever_arquivo_100_arg.nome);

			printf("Digite o que deseja inserir no arquivo: \n");
			fflush(stdin);
			scanf(" %[^\n]s",&escrever_arquivo_100_arg.conteudo);

			printf("Foi escrito: %s\n",escrever_arquivo_100_arg.conteudo);

			result_4 = escrever_arquivo_100(&escrever_arquivo_100_arg, clnt);
			if (result_4 == (int *) NULL) {
				clnt_perror (clnt, "A chamada ao método escrever remoto falhou.");
			}else{
				if(*result_4 == 0){
					printf("Algo deu errado.");				
				}else{
					printf("Operação ESCREVER EM ARQUIVO realizada com sucesso.\n");
				}
			}
		}
	}

	if(opc == 5){
		printf("Digite o nome do arquivo a ser lido: ");
		scanf("%s",&nome);
		strcat(nome,ext);
		strcpy(ler_arquivo_100_arg.nome,nome);
		result_5 = ler_arquivo_100(&ler_arquivo_100_arg, clnt);
		if (result_5 == (int *) NULL) {
			clnt_perror (clnt, "A chamada ao método ler remoto falhou.");
		}else{
			if(*result_5 == 0){
					printf("Algo deu errado.");				
				}else{
					printf("Operação LER ARQUIVO realizada com sucesso.\n");
				}
		}
	}
}while(opc != 0);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	opera_arquivos_100 (host);
exit (0);
}
